---
title: "Cheesecake with Meringue Topping"
author:
  - name: GitUniSF
    url: https://github.com/GitUniSF
---

## {{< fa basket-shopping >}} Ingredients

- [ ] 200 g flour
- [ ] 2 tsp baking powder
- [ ] 2 pinches of iodized salt
- [ ] 100 g + 100 g butter
- [ ] 75 g + 150 g + 75 g sugar
- [ ] 4 eggs
- [ ] 500 g quark (e.g. 20% fat content)
- [ ] 250 g sour cream
- [ ] 250 ml Rama Cremefine for cooking, 15% fat
- [ ] 1 packet of vanilla pudding powder for cooking (about 37 g)
- [ ] 1 packet of vanilla sugar

## {{< fa kitchen-set >}} Procedure

1. Mix 200 g flour, 2 tsp baking powder, and 1 pinch of salt. Knead with 100 g butter, 75 g sugar, and 1 egg using the dough hooks of an electric hand mixer, then by hand until smooth. Line the form with baking paper or grease it, including the edges. Press the dough into the form, creating an edge. Chill the dough in the form until further use.

2. Preheat the oven to 180°C (fan: 160°C). Melt 100 g butter in a pot over low heat. Separate 3 eggs; the egg whites will be used later. Beat the egg yolks with the melted butter, 500 g quark, 250 g sour cream, 250 ml Rama Cremefine, 150 g sugar, pudding powder, and vanilla sugar with the beaters of the electric hand mixer until creamy.

3. Pour the sour cream mixture onto the dough. Bake the cheesecake in the preheated oven for about 60 minutes. If the surface browns too much, cover the cheesecake with aluminum foil.

4. Beat the egg whites with 1 pinch of salt using the (thoroughly cleaned) beaters of the electric hand mixer until stiff, gradually adding 75 g sugar. Spread the meringue on the cheesecake and bake for another 10-15 minutes in the oven. Let the cheesecake with meringue cool and enjoy.

5. If the cake with meringue stands for a while, small golden sugar droplets form on the meringue - a completely natural reaction and a pretty effect. The cheesecake with meringue is therefore also called Tear Cake. For best results, cut the cheesecake with meringue using a knife dipped in hot water.

