# The best _Florentiners_
Florentiner are a German Christmas classic. This new interpretation of it is pretty time consuming but the end result, I promise, is so worth it. Try it out! :)

## Ingredients
For the shortcrust dough:
175 g soft butter
100 g sugar
1 egg
300 g flour
1 pinch of salt
200g dark chocolate

For the topping:
125 ml whipped cream
70 g sugar
30g honey
30g butter
200g ground almonds / flaked almonds
2 tbsp almond kernels
100g dark chocolate coating
Some neutral oil (for shaping the Florentines)
Personal recommendation: dried cranberries (you have to chop them yourself)

## Instructions
(1) Mix the dough ingredients together and knead until it is a firm dough.
(2) Leave the dough to rest for 1 hour.
(3) Roll out the dough very thinly and cut out round shapes. Bake for approx. 5 minutes at 180°C fan oven.
(4) Melt the chocolate and coat the base of the cooled cookies with chocolate.
(5) Leave to harden overnight (or in the fridge).
(6) Heat the whipping cream, sugar, honey and butter in a saucepan, stirring constantly until the mixture caramelizes.
(7) Add the flaked almonds, mix well and cook for 3 minutes, stirring until the mixture begins to brown. Transfer to a bowl, stir in 2 tbsp almond kernels.
Shape the mixture into mounds using 2 oiled teaspoons and place on the cookies. Leave to cool ... and enjoy.


