---
title: "Mac & Cheese"
author: Colleen Dollst
theme: solar
format: html
editor: visual
---

##### This baked mac and cheese is a family favorite recipe, loved by children and adults.

<https://www.thechunkychef.com/family-favorite-baked-mac-and-cheese/#wprm-recipe-container-9151>

## Ingredients

-   1 lb. dried elbow pasta
-   1/2 cup unsalted butter
-   1/2 cup all purpose flour
-   1 1/2 cups whole milk/vegan milk
-   2 1/2 cups half and half/vegan cooking cream
-   4 cups shredded medium cheddar cheese divided (measured after shredding)
-   2 cups shredded Gruyere cheese divided (measured after shredding)
-   1 jalapeño, diced
-   1/2 Tbsp. salt
-   1/2 tsp. black pepper
-   1/4 tsp. paprika smoked paprika is our favorite!
-   1/2 cup panko breadcrumbs (with some butter for toasting)

## Instructions

1.  Preheat oven to 325 degrees F and grease a 3 qt baking dish (9x13"). Set aside.
2.  Bring a large pot of salted water to a boil. When boiling, add dried pasta and cook 1 minute less than the package directs for al dente. Drain and drizzle with a little bit of olive oil to keep from sticking.
3.  While water is coming up to a boil, shred cheeses and toss together to mix, then divide into three piles. Approximately 3 cups for the sauce, 1 1/2 cups for the inner layer, and 1 1/2 cups for the topping.
4.  Melt butter in a large saucepan over MED heat. Sprinkle in flour and whisk to combine. Mixture will look like very wet sand. Cook for approximately 1 minute, whisking often. Slowly pour in about 2 cups or so of the half and half, while whisking constantly, until smooth. Slowly pour in the remaining half and half and the whole milk, while whisking constantly, until combined and smooth.
5.  Continue to heat over MED heat, whisking very often, until thickened to a very thick consistency. It should almost be the consistency of a semi thinned out condensed soup.
6.  Remove from the heat and stir in spices and 1 1/2 cups of the cheeses, stirring to melt and combine. Stir in another 1 1/2 cups of cheese, and stir until completely melted and smooth. Stir in the jalapeño.
7.  In a large mixing bowl, combine drained pasta with cheese sauce, stirring to combine fully. Pour half of the pasta mixture into the prepared baking dish. Top with 1 1/2 cups of shredded cheeses, then top that with the remaining pasta mixture.
8.  Sprinkle the top with the last 1 1/2 cups of cheese and bake for 15 minutes, until cheesy is bubbly and lightly golden brown.
9.  While baking, toast some panko breadcrumbs on the stovetop over medium heat to top the final dish with.

### Tips

-   Please feel free to add additional seasonings per your tastes, this is a base recipe that you can change up to make your own. Garlic powder, onion powder, ground mustard, smoked paprika, and hot sauce are some favorites of ours to add.
-   To get the 4 cups of cheddar, use a 16 oz block of cheddar and shred.
-   To get the 2 cups of gruyere, use as close to an 8 oz block of gruyere as you can (different brands have different sized blocks), and shred.

#### Mac and Cheese can be made ahead:

-   Make as directed (but do not bake), transfer to baking dish and cool completely. Cover tightly with foil and refrigerate 1-2 days ahead.\
-   Before baking, let dish sit on counter for 30 minutes.
-   Bake at recipe temperature for 25-35 minutes, until hot and bubbly.

#### Five cheese Variation:

Replace cheese amounts with the following: \* 2 cups cheddar cheese, shredded \* 1 cup Colby cheese, shredded \* 1 cup Muenster cheese, shredded \* 1 1/2 cups Gruyere cheese, shredded \* 1/2 cup mozzarella cheese, shredded

#### For Crunchier Topping and Firmer Consistency:

Prepare recipe as directed but bake at 350 or 375 F degrees for 20-30 minutes. Broil at the end of baking for approximately 2-5 minutes, until golden brown and crunchy.

Combine with tomatosoup for a perfect meal:

This is my recipe for tomatosoup passed down for generations. The tomatosoup is quite tasty.

Ingredients

Butter – use unsalted butter to sautee onions

Yellow onion – it seems like a ton of onion but it dissapears into the soup adding a balanced sweetness

Garlic – you'll need 1 Tbsp minced from about 3 cloves

Crushed tomatoes – with their juice, preferably

San Marzano tomatoes Chicken stock – for the best flavor use homemade chicken broth Basil – chop and add

1/4 cup fresh basil, plus more to serve. Basil leaves are easily bruised so chop by stacking a bunch of leaves then roll them into a log and cut into thin strips.

Sugar – It's just 1 Tbsp, but necessary to combat the tomato acidity.

Black pepper – start with 1/2 tsp and add more to taste

Whipping cream – adds a creaminess to the soup and offsets acidity.

Parmesan cheese – adds saltiness to the soup and balances acidity. Adding parmesan adds enough salt and I usually don't add more.

Actual Cooking

Saute Aromatics – heat a non-reactive pot over medium heat. Melt in 4 Tbsp butter then sautee onions until softened and golden (10-12 min). Add minced garlic and saute another minute.

Make the tomato soup base – stir in two 28 oz cans of crushed tomatoes with their juice, your chicken stock, chopped basil, sugar and black pepper. Bring to a boil then reduce heat, partially cover and simmer 10 minutes.

Blend if desired – use an immersion blender in the pot or blend in batches using a blender (be careful not to overfill the blender with hot liquid) and return soup to the pot.

Add cream and parmesan – stir in the heavy cream and shredded parmesan. Return to a simmer and season to taste if needed. Serve – ladle into warm bowls and garnish with more parmesan and basil.
