---
title: "Pistachio Macarons"
image: "https://c.gmx.net/@325606737027531506/KMw1LY35QMCnudquRESl3A/ROOT/ROOT
image-alt: "Add the URL to the image here"
categories:
  - sweets
  - perfect as a gift
---

## {{< fa basket-shopping >}} Ingredients

### Ingredient for the Filling:

- [ ] 20g sugar
- [ ] 10g butter
- [ ] 40g chopped pistachio
- [ ] 80g white chocolate
- [ ] 60g whipped cream
- [ ] 1 drop of vanilla

### Ingredients for macarons shells

- [ ] 50g grounded almonds
- [ ] 50g powdered sugar
- [ ] 30g egg white (best if 3 to 5 days old)
- [ ] 13g sugar
- [ ] optional: green food coloring 

### In addition:

- [ ] baking paper for macarons
- [ ] piping bag with round tip

## {{< fa kitchen-set >}} Procedure

1. For the filling you need to reduce the sugar into golden caramel. Take it from the stove and add the butter. After the butter is fully dissolved, add 20g of the chopped pistachios. Now put the pistachio brittle on a baking paper and let it cool down. Mix the rest of the pistachios in the blander. Heat up the white chocolate and whipped cream. Add everything (except the brittle) together and whip it up to a ganache. Keep it in the refrigerator for 20 minutes.
2. Shred the brittle with the blender and mix it under the ganache. Keep the ganache in your refrigerator over night.
3. For the macrons shells mix the grounded almonds and the powdered sugar using the blender. Sieve the mixture until it is a light powder. Mix the egg white until it's white and fluffy. Slowly add the rest of the sugar. Optional you can add the green food coloring now. Fold the egg white in the almond-sugar mix, until you get a gluey dough.
4. Fill dough into piping bag. Put baking paper on a tray. Pipe 24 round spots on the paper. Reduce air pockets in the dough by beating on the pan. Leave baking pan for at least 30 minutes in the room. The shells need to be dry. Preheat the oven up to 160°C and bake the macarons shells for at least 13 minutes (depends on the oven, my oven needs 20 minutes). 
5. Let the macarons shells chill down. Now you can fill them with the ganache and enjoy. 
