# **Tränenkuchen**


**Zutaten**
- 200 g Mehl
- 2 TL Backpulver
- 2 Prisen Jodsalz
- 100 g + 100 g SANELLA
- 75 g + 150 g + 75 g Zucker
- 4 Eier
- 500 g Quark (z.B. 20% Fett i.Tr.)
- 250 g Schmand
- 250 ml Rama Cremefine zum Kochen 15 % Fett
- 1 Beutel Vanillepuddingpulver zum Kochen (ca. 37 g)
- 1 Päckchen Vanillezucker

**Zubereitung**

1. 200 g Mehl, 2 TL Backpulver und 1 Prise Salz vermischen. Mit 100 g Sanella, 75 g Zucker und 1 Ei mit den Knethaken des elektrischen Handrührers und dann mit den Händen zu einem glatten Teig verkneten. Form mit Backpapier auslegen oder fetten, den Rand fetten. Teig in die Form drücken, dabei einen Rand formen. Teig in der Form bis zur weiteren Verwendung kalt stellen.

2. Backofen auf 180 °C (Umluft: 160 °C) vorheizen. 100 g Sanella bei kleiner Hitze im Topf schmelzen. 3 Eier trennen, die Eiweiße werden später benötigt. Eigelbe mit geschmolzener Sanella, 500 g Quark, 250 g Schmand, 250 ml Rama Cremefine, 150 g Zucker, Puddingpulver und Vanillezucker mit den Quirlen des elektrischen Handrührers cremig aufschlagen.

3. Schmand-Masse auf den Teig geben. Käsekuchen im vorgeheizten Ofen ca. 60 Minuten backen, wird die Oberfläche zu stark gebräunt, Käsekuchen mit Alufolie abdecken.

4. Eiweiße mit 1 Prise Salz mit den (gründlich gesäuberten) Quirlen des elektrischen Handrührers steif schlagen, 75 g Zucker dabei einrieseln lassen. Eischnee auf den Käsekuchen streichen und diesen 10-15 weitere Minuten im Ofen backen. Käsekuchen mit Baiser abkühlen lassen und genießen.

Wenn Kuchen mit Eischnee ein wenig steht, bilden sich auf dem Eischnee kleine goldene Zuckertröpfchen - eine ganz natürliche Reaktion und ein hübscher Effekt. Der Käsekuchen mit Baiser wird deshalb auch Tränchenkuchen genannt. Mit einem in heißes Wasser getauchtem Messer lässt sich der Käsekuchen mit Baiser am besten schneiden.

